Ferrocarril/Controllers/BaseOperativasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ferrocarril.Models;

namespace Ferrocarril.Controllers
{
    public class BaseOperativasController : Controller
    {
        private readonly NuevoCentralArgentinoContext _context;

        public BaseOperativasController(NuevoCentralArgentinoContext context)
        {
            _context = context;
        }

        // GET: BaseOperativas
        public async Task<IActionResult> Index()
        {
            return View(await _context.BaseOperativas.ToListAsync());
        }

        // GET: BaseOperativas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var baseOperativa = await _context.BaseOperativas
                .FirstOrDefaultAsync(m => m.IdBase == id);
            if (baseOperativa == null)
            {
                return NotFound();
            }

            return View(baseOperativa);
        }

        // GET: BaseOperativas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BaseOperativas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdBase,Descripcion,Ubicacion")] BaseOperativa baseOperativa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(baseOperativa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(baseOperativa);
        }

        // GET: BaseOperativas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var baseOperativa = await _context.BaseOperativas.FindAsync(id);
            if (baseOperativa == null)
            {
                return NotFound();
            }
            return View(baseOperativa);
        }

        // POST: BaseOperativas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdBase,Descripcion,Ubicacion")] BaseOperativa baseOperativa)
        {
            if (id != baseOperativa.IdBase)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(baseOperativa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BaseOperativaExists(baseOperativa.IdBase))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(baseOperativa);
        }

        // GET: BaseOperativas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var baseOperativa = await _context.BaseOperativas
                .FirstOrDefaultAsync(m => m.IdBase == id);
            if (baseOperativa == null)
            {
                return NotFound();
            }

            return View(baseOperativa);
        }

        // POST: BaseOperativas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var baseOperativa = await _context.BaseOperativas.FindAsync(id);
            if (baseOperativa != null)
            {
                _context.BaseOperativas.Remove(baseOperativa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BaseOperativaExists(int id)
        {
            return _context.BaseOperativas.Any(e => e.IdBase == id);
        }
    }
}

Ferrocarril/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ferrocarril.Models;

namespace Ferrocarril.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly NuevoCentralArgentinoContext _context;

        public EmpleadoController(NuevoCentralArgentinoContext context)
        {
            _context = context;
        }

        // GET: Empleado
        public async Task<IActionResult> Index()
        {
            var nuevoCentralArgentinoContext = _context.Empleados.Include(e => e.BaseOperativa).Include(e => e.Categoria).Include(e => e.Servicio);
            return View(await nuevoCentralArgentinoContext.ToListAsync());
        }

        // GET: Empleado/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .Include(e => e.BaseOperativa)
                .Include(e => e.Categoria)
                .Include(e => e.Servicio)
                .FirstOrDefaultAsync(m => m.Legajo == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleado/Create
        public IActionResult Create()
        {
            ViewData["ListaBase"] = new SelectList(_context.BaseOperativas, "IdBase", "Descripcion");
            ViewData["ListaServicio"] = new SelectList(_context.Servicios, "IdServicio", "Descripcion");
            ViewData["ListaCategoria"] = new SelectList(_context.Categorias, "IdCategoria", "Descripcion");
            return View();
        }

        // POST: Empleado/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Legajo,Nombre,Apellido,FechaIngreso")] Empleado empleado, int IdServicio, int IdBase, int IdCategoria)
        {

            empleado.BaseOperativaId = IdBase;
            empleado.ServicioId = IdServicio;
            empleado.CategoriaId = IdCategoria;

            if (empleado != null)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BaseOperativaId"] = new SelectList(_context.BaseOperativas, "IdBase", "IdBase", empleado.BaseOperativaId);
            ViewData["ServicioId"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", empleado.ServicioId);
            return View(empleado);
        }

        // GET: Empleado/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            ViewData["ListaBase"] = new SelectList(_context.BaseOperativas, "IdBase", "Descripcion",empleado.BaseOperativaId);
            ViewData["ListaServicio"] = new SelectList(_context.Servicios, "IdServicio", "Descripcion", empleado.ServicioId);
            ViewData["ListaCategoria"] = new SelectList(_context.Categorias, "IdCategoria", "Descripcion", empleado.CategoriaId);
            
            return View(empleado);
        }

        // POST: Empleado/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Legajo,Nombre,Apellido,FechaIngreso,BaseOperativaId,ServicioId,CategoriaId")] Empleado empleado)
        {
            if (id != empleado.Legajo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.Legajo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ListaBase"] = new SelectList(_context.BaseOperativas, "IdBase", "Descripcion", empleado.BaseOperativaId);
            ViewData["ListaServicio"] = new SelectList(_context.Servicios, "IdServicio", "Descripcion", empleado.ServicioId);
            ViewData["ListaCategoria"] = new SelectList(_context.Categorias, "IdCategoria", "Descripcion", empleado.CategoriaId);
            return View(empleado);
        }

        // GET: Empleado/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .Include(e => e.BaseOperativa)
                .Include(e => e.Categoria)
                .Include(e => e.Servicio)
                .FirstOrDefaultAsync(m => m.Legajo == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado != null)
            {
                _context.Empleados.Remove(empleado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleados.Any(e => e.Legajo == id);
        }
    }
}

Ferrocarril/Controllers/HomeController.cs
using Ferrocarril.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Ferrocarril.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ferrocarril/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<br />

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-100">
            <img class="card-img-top" src="~/Imagenes/nca.jpg" alt="Bases Operativas">
            <a class="btn btn-primary" asp-controller="BaseOperativas" asp-action="Create"><i class="fa-solid fa-train fa-shake fa-lg" style="color: #ffffff;"></i><i class="fa-solid fa-plus fa-sm" style="color: #ffffff;"></i></a>
            <div class="card-body">
                <h5 class="card-title">Bases Operativas</h5>
                <p class="card-text">En esta seccion podrás visualizar con detalles nuevas Bases Operativas, conoceras donde están ubicadas, podrás editar sus datos y  eliminarlas si fuera necesario .</p>

                <form asp-controller="BaseOperativas" asp-action="Index">
                    <input type="submit" value="Ver más..." class="btn btn-primary btn-sm" />
                </form>
            </div>
            <div class="card-footer">
                <small class="text-muted"></small>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <img src="~/Imagenes/Empleado.jpg" class="card-img-top" alt="Foto Empleados">
            <a class="btn btn-primary" asp-controller="Empleado" asp-action="Create"><i class="fa-solid fa-train fa-shake fa-lg" style="color: #ffffff;"></i><i class="fa-solid fa-plus fa-sm" style="color: #ffffff;"></i></a>
            <div class="card-body">
                <h5 class="card-title">Nuestros Operarios</h5>
                <p class="card-text">En esta seccion podrás conocer a todos nuestros operarios, visualizar detalles de cada uno, como también agregar nuevos, actualizar datos y eliminarlos si fuera necesario.</p>
                <form asp-controller="Empleado" asp-action="Index">
                    <input type="submit" value="Ver más..." class="btn btn-primary btn-sm" />
                </form>
            </div>
            <div class="card-footer">
                <small class="text-muted"></small>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
            <img src="~/Imagenes/categoria.jpg" class="card-img-top" alt="foto categorias">
            <a class="btn btn-primary" asp-controller="Categoria" asp-action="Post"><i class="fa-solid fa-train fa-shake fa-lg" style="color: #ffffff;"></i><i class="fa-solid fa-plus fa-sm" style="color: #ffffff;"></i></a>
            <div class="card-body">
                <h5 class="card-title">Categorias</h5>
                <p class="card-text">En esta sección conocerás todas la especialidades desarrolladas en nuestra empresa, conoceras en algunos detalles como tambien actualizar datos y eliminarlos si fuera necesario .</p>
                <form asp-controller="Categoria" asp-action="Index">
                    <input type="submit" value="Ver más..." class="btn btn-primary btn-sm" />
                </form>
            </div>
            <div class="card-footer">
                <small class="text-muted"></small>
            </div>
        </div>
    </div>
</div>